### ISSUE TITLE
Deploy to Google Play Store

### ISSUE THREAD

**Issue by raae** [bGraphic/varsom-hybrid#153]
Figure out what is needed and create tasks.

- [x] Fix styling of sidebar on Android #157
- [x] Get keystore from Kjell Ivar
- [x] Create listing on Google Play #158
- [x] Create resouces using ionic cli #160
- [x] Make sure push works on Android
- [ ] Create bundle with correct certifictates etc
- [ ] Upload and test

**Comment by raae** [comment]
Spurt Kjell Ivar om det var sånn at keystoren vi trenger for å oppdatere eksiterende app er mistet. Ganske sikkert på det, men ville dobbeltsjekke.

**Comment by raae** [comment]
Den er borte, men Kjell Ivar anbefaler å bruke samme som på RegObs så blir det mindre å holde styr på.

**Comment by raae** [comment]
Utsette push for Android meldinger for Android. Viktigst å få den ut nå.
